title: Maulik Madhavi
logo: "/images/mypic.jpg"
description: >
  <a href="https://www.linkedin.com/in/maulik-madhavi-25743b82/">LinkedIn</a> |
  <a href="https://github.com/maulikmadhavi">GitHub</a> |
  <a href="https://scholar.google.com/citations?user=BLLXxDoAAAAJ&hl=en">Google Scholar</a> |
  <a href="https://www.researchgate.net/profile/Maulik-Madhavi">ResearchGate</a>

# Theme
remote_theme: pages-themes/time-machine@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
